name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-meson mingw-w64-x86_64-ninja mingw-w64-x86_64-pkg-config  mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-glew
      - name: Build Hades
        run: |
          meson build -Dstatic_executable=true
          cd build
          ninja
      - name: Test Hades
        run: |
          cd build
          ./source/platform/gui/hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-win64
          path: build/source/platform/gui/Hades.exe
          if-no-files-found: error

  mac-os:
    runs-on: macos-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          brew install meson ninja sdl2 glew
      - name: Build Hades
        run: |
          meson --buildtype=release --prefix=/tmp/hades.app --bindir=Content/MacOS build --werror
          ninja -C build install
      - name: Test Hades
        run: |
          cd build
          ./source/plateform/gui/hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-macos
          path: /tmp/hadds.app
          if-no-files-found: error

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build libsdl2-dev libglew-dev
      - name: Build Hades
        run: |
          meson build --werror
          cd build
          ninja
      - name: Test Hades
        run: |
          cd build
          ./source/platform/gui/hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-linux
          path: build/source/platform/gui/hades
          if-no-files-found: error
